apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello
resources:
  - services.yaml
  - deployment-v1.yaml
  - deployment-v2.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - httproute.yaml
configMapGenerator:
  - { name: angie-v1, files: [angie.conf=angie-v1.conf] }
  - { name: angie-v2, files: [angie.conf=angie-v2.conf] }
